# Change these first
owner: 503stack # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Harbor
    url: https://cr.fredhs.net
  - name: Joplin
    url: https://joplin.fredhs.net
  - name: Minio
    url: https://console.minio.fredhs.net
  - name: Privatebin
    url: https://bin.fredhs.net
  - name: Harbor ipv6
    url: https://cr.fredhs.net
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: 503stack.xyz
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 503stack
  introTitle: "**503stack** uptime monitor and status page"
  introMessage: Powered entirely by GitHub
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
